# Set up ----
# Import personal functions to use across scripts
source(here::here("scripts", "general_functions.R"))

# Packages ----

# Vector holding the list of packages that will be used
analysis_packs<-c("here", "tictoc", "beepr", "tidyverse", "ggtext", "ragg")

# Install packages not yet installed
install_new_packs(analysis_packs)

# Load packages
load_my_packs(analysis_packs)

# Load custom ggplot themes
source(here("scripts", "custom_ggplot_themes.R"))

# A vector to contain the names of the objects generated by the master script
## Any object named within this vector will be preserved in the environment
## after the environment cleaning last steps of each script
analysis_objects <- c(ls(), "analysis_objects")

# Data -----
source(here("scripts", "data.R"))

# EDA ----
batch <- "full"
analysis_objects <- c(analysis_objects, "batch")
source(here("scripts", "eda.R")); beep("complete")

# PCA ----
source(here("scripts", "pca.R")); beep("complete")

# LDA ----
source(here("scripts", "lda.R")); beep("complete")

# lm ----
source(here("scripts", "lm.R")); beep("complete")

# random forest ----
source(here("sripts", "random_forest.R"))

# Knit rmarkdown files ----
## Make a list of all the rmd files in the repository
rmd_list <- list.files(path = here()
                       , pattern = ".Rmd"
                       , full.names = T
                       , recursive = T) 

readmes_list <- rmd_list |> 
  str_subset("README")

## Knit the all the README files
lapply(rmd_list, my_knit_md)

## Report session information
capture.output(sessionInfo()
               , file = here("output"
                             ,"SInf_analysis-master-script.txt"))
