# tictoc::tic("Analysis master script")

# Set up ----
# package here and pacman are needed to begin to use the code within the project
install.packages("here")
install.packages("pacman")

# Import personal functions to use across scripts
source(here::here("scripts", "general_functions.R"))

# Packages ----

# Vector holding the list of packages that will be used
analysis_packs <- c("here", "tictoc", "beepr", "tidyverse", "ggtext", "ragg")

# install / load packages
load_my_packs(analysis_packs)

# Load custom ggplot themes
source(here("scripts", "custom_ggplot_themes.R"))

# A vector to contain the names of the objects generated by the master script
## Any object named within this vector will be preserved in the environment
## after the environment cleaning last steps of each script
analysis_objects <- c(ls(), "analysis_objects")

# Data -----
source(here("scripts", "data.R"))

# EDA ----
#  options: full, Biscoe, Dream, Torgersen
batch <- "full" 
analysis_objects <- c(analysis_objects, "batch")
source(here("scripts", "eda.R")); beep()

# PCA ----
source(here("scripts", "pca.R")); beep()

# LDA ----
source(here("scripts", "lda.R")); beep()

# lm ----
source(here("scripts", "lm.R")); beep()

# random forest ----
source(here("scripts", "random_forest.R")); beep()

# Knit rmarkdown files ----
## Make a list of all the rmd files in the repository
rmd_list <- list.files(path = here()
                       , pattern = ".Rmd"
                       , full.names = T
                       , recursive = T) |> 
  # Avoid package library files
  str_subset('/renv/', negate = T) 

readmes_list <- rmd_list |> 
  # Only README files
  str_subset("README") 

## Knit the all the README files
lapply(rmd_list, my_knit_md)

## Report session information
capture.output(sessionInfo()
               , file = here("output"
                             ,"SInf_analysis-master-script.txt"))

# tictoc::toc(); beep("complete")
